In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


In [3]:
#Create a NumPy ndarray Object
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
#Check how many dimensions the arrays have:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


# PANDAS

In [8]:
import pandas as pd

In [9]:
print(pd.__version__)

1.1.3


In [10]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2],
  'price':[200000,'NaN',2300000],
  'owner': ["Aman", "Sham", "NaN"],
}

myvar = pd.DataFrame(mydataset)

print(myvar)


    cars  passings    price owner
0    BMW         3   200000  Aman
1  Volvo         7      NaN  Sham
2   Ford         2  2300000   NaN


In [11]:
import pandas as pd

df = pd.read_csv('Bengaluru_House_Data.csv')

df.head() 

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [12]:
df.head(10)

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   
5  Super built-up  Area  Ready To Move                Whitefield      2 BHK   
6  Super built-up  Area         18-May          Old Airport Road      4 BHK   
7  Super built-up  Area  Ready To Move              Rajaji Nagar      4 BHK   
8  Super built-up  Area  Ready To Move              Marathahalli      3 BHK   
9            Plot  Area  Ready To Move              Gandhi Bazar  6 Bedroom   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00  
5  DuenaTa       1170   2.0      1.0   38.00  
6  Jaades        2732   4.0      NaN  204.00  
7  Brway G       3300   4.0      NaN  600.00  
8      NaN       1310   3.0      1.0   63.25  
9      NaN       1020   6.0      NaN  370.00

In [13]:
(df.tail()) 

area_type   availability               location       size  \
13315        Built-up  Area  Ready To Move             Whitefield  5 Bedroom   
13316  Super built-up  Area  Ready To Move          Richards Town      4 BHK   
13317        Built-up  Area  Ready To Move  Raja Rajeshwari Nagar      2 BHK   
13318  Super built-up  Area         18-Jun        Padmanabhanagar      4 BHK   
13319  Super built-up  Area  Ready To Move           Doddathoguru      1 BHK   

       society total_sqft  bath  balcony  price  
13315  ArsiaEx       3453   4.0      0.0  231.0  
13316      NaN       3600   5.0      NaN  400.0  
13317  Mahla T       1141   2.0      1.0   60.0  
13318  SollyCl       4689   4.0      1.0  488.0  
13319      NaN        550   1.0      1.0   17.0

In [14]:
df.tail(10)

area_type   availability               location       size  \
13310  Super built-up  Area  Ready To Move           Rachenahalli      2 BHK   
13311            Plot  Area  Ready To Move       Ramamurthy Nagar  7 Bedroom   
13312  Super built-up  Area  Ready To Move              Bellandur      2 BHK   
13313  Super built-up  Area  Ready To Move            Uttarahalli      3 BHK   
13314  Super built-up  Area  Ready To Move      Green Glen Layout      3 BHK   
13315        Built-up  Area  Ready To Move             Whitefield  5 Bedroom   
13316  Super built-up  Area  Ready To Move          Richards Town      4 BHK   
13317        Built-up  Area  Ready To Move  Raja Rajeshwari Nagar      2 BHK   
13318  Super built-up  Area         18-Jun        Padmanabhanagar      4 BHK   
13319  Super built-up  Area  Ready To Move           Doddathoguru      1 BHK   

       society total_sqft  bath  balcony   price  
13310      NaN       1050   2.0      2.0   52.71  
13311      NaN       1500   9.0      2.0  250.00  
13312      NaN       1262   2.0      2.0   47.00  
13313  Aklia R       1345   2.0      1.0   57.00  
13314  SoosePr       1715   3.0      3.0  112.00  
13315  ArsiaEx       3453   4.0      0.0  231.00  
13316      NaN       3600   5.0      NaN  400.00  
13317  Mahla T       1141   2.0      1.0   60.00  
13318  SollyCl       4689   4.0      1.0  488.00  
13319      NaN        550   1.0      1.0   17.00

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13319 non-null  object 
 3   size          13304 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


In [16]:
#1. Return a new Data Frame with no empty cells:
df = pd.read_csv('dirtydata.csv')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  32 non-null     int64  
 1   Date      31 non-null     object 
 2   Pulse     32 non-null     int64  
 3   Maxpulse  32 non-null     int64  
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB


In [18]:
df

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [19]:
new_df = df.dropna()
new_df

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [20]:
df.fillna("Hello", inplace = True)
df

Duration          Date  Pulse  Maxpulse Calories
0         60  '2020/12/01'    110       130    409.1
1         60  '2020/12/02'    117       145      479
2         60  '2020/12/03'    103       135      340
3         45  '2020/12/04'    109       175    282.4
4         45  '2020/12/05'    117       148      406
5         60  '2020/12/06'    102       127      300
6         60  '2020/12/07'    110       136      374
7        450  '2020/12/08'    104       134    253.3
8         30  '2020/12/09'    109       133    195.1
9         60  '2020/12/10'     98       124      269
10        60  '2020/12/11'    103       147    329.3
11        60  '2020/12/12'    100       120    250.7
12        60  '2020/12/12'    100       120    250.7
13        60  '2020/12/13'    106       128    345.3
14        60  '2020/12/14'    104       132    379.3
15        60  '2020/12/15'     98       123      275
16        60  '2020/12/16'     98       120    215.2
17        60  '2020/12/17'    100       120      300
18        45  '2020/12/18'     90       112    Hello
19        60  '2020/12/19'    103       123      323
20        45  '2020/12/20'     97       125      243
21        60  '2020/12/21'    108       131    364.2
22        45         Hello    100       119      282
23        60  '2020/12/23'    130       101      300
24        45  '2020/12/24'    105       132      246
25        60  '2020/12/25'    102       126    334.5
26        60      20201226    100       120      250
27        60  '2020/12/27'     92       118      241
28        60  '2020/12/28'    103       132    Hello
29        60  '2020/12/29'    100       132      280
30        60  '2020/12/30'    102       129    380.3
31        60  '2020/12/31'     92       115      243

In [23]:
df["Calories"].fillna("Again Filled Hello", inplace = True)
df

Duration          Date  Pulse  Maxpulse Calories
0         60  '2020/12/01'    110       130    409.1
1         60  '2020/12/02'    117       145      479
2         60  '2020/12/03'    103       135      340
3         45  '2020/12/04'    109       175    282.4
4         45  '2020/12/05'    117       148      406
5         60  '2020/12/06'    102       127      300
6         60  '2020/12/07'    110       136      374
7        450  '2020/12/08'    104       134    253.3
8         30  '2020/12/09'    109       133    195.1
9         60  '2020/12/10'     98       124      269
10        60  '2020/12/11'    103       147    329.3
11        60  '2020/12/12'    100       120    250.7
12        60  '2020/12/12'    100       120    250.7
13        60  '2020/12/13'    106       128    345.3
14        60  '2020/12/14'    104       132    379.3
15        60  '2020/12/15'     98       123      275
16        60  '2020/12/16'     98       120    215.2
17        60  '2020/12/17'    100       120      300
18        45  '2020/12/18'     90       112    Hello
19        60  '2020/12/19'    103       123      323
20        45  '2020/12/20'     97       125      243
21        60  '2020/12/21'    108       131    364.2
22        45         Hello    100       119      282
23        60  '2020/12/23'    130       101      300
24        45  '2020/12/24'    105       132      246
25        60  '2020/12/25'    102       126    334.5
26        60      20201226    100       120      250
27        60  '2020/12/27'     92       118      241
28        60  '2020/12/28'    103       132    Hello
29        60  '2020/12/29'    100       132      280
30        60  '2020/12/30'    102       129    380.3
31        60  '2020/12/31'     92       115      243

In [22]:
#To fix it, you have two options: remove the rows, or convert all cells in the columns into the same format.
df['Date'] = pd.to_datetime(df['Date'])
df

ParserError: Unknown string format: Hello

In [ ]:
#to fix wrong data
#Set "Duration" = 45 in row 7:

df.loc[7, 'Duration'] = 45
df

Discovering Duplicates

In [24]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool


In [25]:
#Remove all duplicates:
df.drop_duplicates(inplace = True)
df

Duration          Date  Pulse  Maxpulse Calories
0         60  '2020/12/01'    110       130    409.1
1         60  '2020/12/02'    117       145      479
2         60  '2020/12/03'    103       135      340
3         45  '2020/12/04'    109       175    282.4
4         45  '2020/12/05'    117       148      406
5         60  '2020/12/06'    102       127      300
6         60  '2020/12/07'    110       136      374
7        450  '2020/12/08'    104       134    253.3
8         30  '2020/12/09'    109       133    195.1
9         60  '2020/12/10'     98       124      269
10        60  '2020/12/11'    103       147    329.3
11        60  '2020/12/12'    100       120    250.7
13        60  '2020/12/13'    106       128    345.3
14        60  '2020/12/14'    104       132    379.3
15        60  '2020/12/15'     98       123      275
16        60  '2020/12/16'     98       120    215.2
17        60  '2020/12/17'    100       120      300
18        45  '2020/12/18'     90       112    Hello
19        60  '2020/12/19'    103       123      323
20        45  '2020/12/20'     97       125      243
21        60  '2020/12/21'    108       131    364.2
22        45         Hello    100       119      282
23        60  '2020/12/23'    130       101      300
24        45  '2020/12/24'    105       132      246
25        60  '2020/12/25'    102       126    334.5
26        60      20201226    100       120      250
27        60  '2020/12/27'     92       118      241
28        60  '2020/12/28'    103       132    Hello
29        60  '2020/12/29'    100       132      280
30        60  '2020/12/30'    102       129    380.3
31        60  '2020/12/31'     92       115      243

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Duration  31 non-null     int64 
 1   Date      31 non-null     object
 2   Pulse     31 non-null     int64 
 3   Maxpulse  31 non-null     int64 
 4   Calories  31 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.5+ KB


# Finding Relationships
A great aspect of the Pandas module is the corr() method.

The corr() method calculates the relationship between each column in your data set.

In [ ]:
df.corr()

The number varies from -1 to 1.

1 means that there is a 1 to 1 relationship (a perfect correlation), and for this data set, each time a value went up in the first column, the other one went up as well.

0.9 is also a good relationship, and if you increase one value, the other will probably increase as well.

-0.9 would be just as good relationship as 0.9, but if you increase one value, the other will probably go down.

0.2 means NOT a good relationship, meaning that if one value goes up does not mean that the other will.

PLOTING:

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

1. Scatter Plot

In [ ]:
plt.scatter(x="Duration",y="Pulse")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])

plt.scatter(x, y)
plt.show()

Size
You can change the size of the dots with the s argument.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.array([5,7,8,7,2,17,2,9,4,11,12,9,6])
y = np.array([99,86,87,88,111,86,103,87,94,78,77,85,86])
sizes = np.array([20,50,100,200,500,1000,60,90,10,300,600,800,75])

plt.scatter(x, y, s=sizes)

plt.show()

HISTOGRAM

In [ ]:
plt.hist(df.Duration,rwidth=0.8)